import { atom } from "recoil";

export const sub = atom({
    key: 'sub',
    default: [
        {
            id: 5,
            name: "Computer Science",
            credits: 3,
            teachers: "Jane Smith",
            teacherId: 2,
            applicationStatus: "Approved",
            slot: "E1, E2, E3",
        },
        {
            id: 6,
            name: "English Literature",
            credits: 3,
            teachers: "Alice Johnson",
            teacherId: 3,
            applicationStatus: "Pending",
            slot: "F1, F2, F3",
        },
        {
            id: 7,
            name: "History",
            credits: 3,
            teachers: "Michael Brown",
            teacherId: 4,
            applicationStatus: "No",
            slot: "G1, G2, G3",
        },
        {
            id: 8,
            name: "Economics",
            credits: 3,
            teachers: "Chris Davis",
            teacherId: 5,
            applicationStatus: "Approved",
            slot: "H1, H2, H3",
        },
        {
            id: 9,
            name: "Psychology",
            credits: 3,
            teachers: "Emily White",
            teacherId: 6,
            applicationStatus: "Pending",
            slot: "I1, I2, I3",
        },
        {
            id: 10,
            name: "Sociology",
            credits: 3,
            teachers: "Robert Green",
            teacherId: 7,
            applicationStatus: "No",
            slot: "J1, J2, J3",
        },
        {
            id: 11,
            name: "Political Science",
            credits: 3,
            teachers: "Linda Miller",
            teacherId: 8,
            applicationStatus: "Approved",
            slot: "K1, K2, K3",
        },
        {
            id: 12,
            name: "Art",
            credits: 3,
            teachers: "David Wilson",
            teacherId: 9,
            applicationStatus: "Pending",
            slot: "L1, L2, L3",
        },
        {
            id: 13,
            name: "Geography",
            credits: 3,
            teachers: "Karen Taylor",
            teacherId: 10,
            applicationStatus: "No",
            slot: "M1, M2, M3",
        },
        {
            id: 14,
            name: "Music",
            credits: 3,
            teachers: "Brian Harris",
            teacherId: 11,
            applicationStatus: "Approved",
            slot: "N1, N2, N3",
        },
        {
            id: 15,
            name: "Physical Education",
            credits: 3,
            teachers: "Jessica Martinez",
            teacherId: 12,
            applicationStatus: "Pending",
            slot: "O1, O2, O3",
        },
        {
            id: 16,
            name: "Environmental Science",
            credits: 3,
            teachers: "Samuel Adams",
            teacherId: 13,
            applicationStatus: "No",
            slot: "P1, P2, P3",
        },
        {
            id: 17,
            name: "Philosophy",
            credits: 3,
            teachers: "Olivia Turner",
            teacherId: 14,
            applicationStatus: "Approved",
            slot: "Q1, Q2, Q3",
        },
        {
            id: 18,
            name: "Foreign Language (Spanish)",
            credits: 3,
            teachers: "Carlos Rodriguez",
            teacherId: 15,
            applicationStatus: "Pending",
            slot: "R1, R2, R3",
        },
        {
            id: 19,
            name: "Business Studies",
            credits: 3,
            teachers: "Sophie Lewis",
            teacherId: 16,
            applicationStatus: "No",
            slot: "S1, S2, S3",
        },
        {
            id: 20,
            name: "Health Science",
            credits: 3,
            teachers: "Matthew Wright",
            teacherId: 17,
            applicationStatus: "Approved",
            slot: "T1, T2, T3",
        },
        {
            id: 21,
            name: "Drama",
            credits: 3,
            teachers: "Grace Campbell",
            teacherId: 18,
            applicationStatus: "Pending",
            slot: "U1, U2, U3",
        },
        {
            id: 22,
            name: "Astronomy",
            credits: 3,
            teachers: "Daniel Johnson",
            teacherId: 19,
            applicationStatus: "No",
            slot: "V1, V2, V3",
        },
        {
            id: 23,
            name: "Engineering",
            credits: 3,
            teachers: "Anthony Davis",
            teacherId: 20,
            applicationStatus: "Approved",
            slot: "W1, W2, W3",
        },
        {
            id: 24,
            name: "Culinary Arts",
            credits: 3,
            teachers: "Isabella Garcia",
            teacherId: 21,
            applicationStatus: "Pending",
            slot: "X1, X2, X3",
        },
        {
            id: 25,
            name: "Graphic Design",
            credits: 3,
            teachers: "Nathan White",
            teacherId: 22,
            applicationStatus: "No",
            slot: "Y1, Y2, Y3",
        },
        {
            id: 26,
            name: "Statistics",
            credits: 3,
            teachers: "Erica Brown",
            teacherId: 23,
            applicationStatus: "Approved",
            slot: "Z1, Z2, Z3",
        }]
});